[tool.poetry]
name = "glocaltokens"
version = "0.0.0"
description = "Python package to fetch google home local authentication tokens"
authors = ["Ilja Leiko <leikoilja@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
gpsoauth = "^0.4.3"
grpcio = "1.31.0"
grpcio-tools = "1.31.0"
simplejson = "^3.17.2"
requests = "^2.25.1"
zeroconf = "^0.28.8"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.9.0"
pre-commit = "^2.11.1"
pylint = "^2.7.2"
isort = "^5.8.0"
mypy = "^0.812"
tox = "^3.23.0"
pytest = "^6.2.2"
Faker = "^6.6.2"
mock = "^4.0.3"

[tool.pylint.format]
max-line-length = 88

[tool.isort]
profile = "black"
force_sort_within_sections = true
combine_as_imports = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
